### ISSUE TITLE
OtaUpdate is !Send

### ISSUE THREAD

**Issue by mhthies** [faern/esp-ota#6]
The `OtaUpdate` struct does not implement the auto-impl trait `Send` because it contains the `partition` raw pointer. However, as far as I understand, it is safe to transfer the pointer to another thread (i.e. FreeRTOS task) as it is only a marker for the used OTA partition and does not provide shared ownership of data or similar.

So a simple `unsafe impl Send for OtaUpdate {}` should not hurt, does it?

For my usecase I need the OtaUpdate struct to be `Send` to borrow from a callback method of the esp_idf_hal framework, which is executed in a separate FreeRTOS task and thus declared as `FnMut(...) + Send + '...`.

**Comment by faern** [comment]
Long time since I looked into the details of this. I have not needed it to be `Send` so I have not paid attention to that (yet). Can you please link to some espressif documentation claiming it's safe to do different OTA writes from different threads?

**Comment by mhthies** [comment]
I'm afraid, there is no such documentation. All [the ESP OTA update documentation](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/ota.html) does not consider FreeRTOS tasks at all.

I would assume that different tasks do not make any difference when continuing an OTA update. And requiring an `&mut self` reference should protect us from concurrently executing the `OtaUpdate::write()` method from multiple threads.

**Comment by faern** [comment]
It does looks like the `esp-idf-svc` implementation of the same thing does implement `Send`. So I guess they figured it's safe? https://docs.esp-rs.org/esp-idf-svc/esp_idf_svc/ota/struct.EspOtaUpdate.html#impl-Send-for-EspOtaUpdate%3C'a%3E

I'm OK with making it `Send` then. Would you be willing to provide a PR?
